In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.16.4


In [4]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

# question 1

In [5]:
arr=np.arange(2,50,3)

In [6]:
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# question 2

In [9]:
l1=[]
l2=[]
for i in range(0,5):    
    a=int(input("Enter element of first list : "))
    l1.append(a)
for i in range(0,5):    
    a=int(input("Enter element of second list : "))
    l1.append(a)

arr1=np.array(l1)
arr2=np.array(l2)

arr=np.concatenate((arr1, arr2))
print(np.sort(arr))



Enter element of first list : 4
Enter element of first list : 1
Enter element of first list : 2
Enter element of first list : 5
Enter element of first list : 3
Enter element of second list : 6
Enter element of second list : 9
Enter element of second list : 8
Enter element of second list : 7
Enter element of second list : 0
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# Question 3

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print("dimension is : ",arr.ndim)
print("Size is : ",arr.size)

(3, 3)
dimension is :  2
Size is :  9


# Question 4

In [14]:

import numpy as np
array1 = np.arange(10)
print("Shape: ",array1.shape)
#converting in row wise
row_array = array1[np.newaxis, :]
print("Shape of 2D Array in row: ",row_array.shape)
#converting in column wise
col_array = array1[:, np.newaxis]
print("Shape of 2D Array in column: ",col_array.shape)

Shape:  (10,)
Shape of 2D Array in row:  (1, 10)
Shape of 2D Array in column:  (10, 1)


# Question 5

In [15]:
array1 = np.square([1, 2, 3, 4, 5])
array2 = np.square([6,86,55,69,75])

print("Horizontal Stack : ", np.hstack((array1, array2)))
print("Vertical Stack : ", np.vstack((array1, array2)))

Horizontal Stack :  [   1    4    9   16   25   36 7396 3025 4761 5625]
Vertical Stack :  [[   1    4    9   16   25]
 [  36 7396 3025 4761 5625]]


# Question 6

In [16]:
import numpy as np
array1 = np.array([2,5,3,7,6,9,8,25,36,42,15,6,6,5,1,2,85,96,37,46,8,122,365,77])

unique, counts = np.unique(array1, return_counts=True)
array2 = np.asarray((unique, counts)).T
print(array2)

[[  1   1]
 [  2   2]
 [  3   1]
 [  5   2]
 [  6   3]
 [  7   1]
 [  8   2]
 [  9   1]
 [ 15   1]
 [ 25   1]
 [ 36   1]
 [ 37   1]
 [ 42   1]
 [ 46   1]
 [ 77   1]
 [ 85   1]
 [ 96   1]
 [122   1]
 [365   1]]
